language: ruby
rvm:
- 2.3.1

before_install:
- openssl aes-256-cbc -K $encrypted_6059a4f451fd_key -iv $encrypted_6059a4f451fd_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- echo -e "Host zeus.ugent.be\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
- bundle install --without development

script:
- bundle exec nanoc
- bundle exec nanoc check elinks
- bundle exec nanoc check ilinks
- bundle exec nanoc check stale
- bundle exec nanoc check mixed_content

after_success:
- chmod 600 ~/.ssh/id_rsa
- bundle exec nanoc deploy --target public
