language: ruby
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_6059a4f451fd_key -iv $encrypted_6059a4f451fd_iv
  -in id_rsa.enc -out .ssh/id_rsa -d

install:
- bundle install --without development

script:
- bundle exec nanoc check elinks
- bundle exec nanoc check ilinks
- bundle exec nanoc check stale
- bundle exec nanoc check mixed_content
- bundle exec nanoc

after_success:
- bundle exec nanoc deploy --target public
